export {default as Navbar } from './Navbar'
export {default as HeroSection } from './HeroSection'
export {default as Sidebar } from './Sidebar'
export {default as InfoSection } from './InfoSection'
export {default as MentorSection} from './MentorSection'
export {default as Services } from './Services'
export {default as Footer } from './Footer'